name: Deploy Infrastructure

'on':
  # push: # Not yet
  #   branches:
  #     - main
  workflow_dispatch:

    null
permissions:
  id-token: write # Required for OIDC
  contents: read

env:
  N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # PASTE YOUR ROLE ARN FROM STEP 2 HERE
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Install Checkov
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip pipx
          pipx ensurepath
          export PATH="$HOME/.local/bin:$PATH"
          pipx install checkov

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init

      - name: Run Checkov
        working-directory: ../
        run: checkov -d ./Terraform

      - name: Terraform Apply
        working-directory: ./Terraform
        # We use -auto-approve because there is no human to type "yes"
        run: terraform apply -auto-approve
        env:
          # Add this secret in GitHub Repo Settings -> Secrets
          TF_VAR_N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}